# =============================================
# postgresql.conf — BookingHub
# =============================================

# Aceitar conexões de qualquer endereço (necessário para Docker)
listen_addresses = '*'

# Conexões
max_connections = 100

# Memória
shared_buffers = 128MB
work_mem = 16MB

# WAL
wal_level = replica
archive_mode = on
archive_command = 'cp %p /wal_archive/%f'
archive_timeout = 60

# Checkpoints
checkpoint_completion_target = 0.9

# Logs
log_min_duration_statement = 100
log_checkpoints = on
log_lock_waits = on
